(function() {var implementors = {};
implementors["cassowary"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"cassowary/struct.Variable.html\" title=\"struct cassowary::Variable\">Variable</a>",synthetic:false,types:["cassowary::Variable"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"cassowary/struct.Term.html\" title=\"struct cassowary::Term\">Term</a>",synthetic:false,types:["cassowary::Term"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"cassowary/enum.RelationalOperator.html\" title=\"enum cassowary::RelationalOperator\">RelationalOperator</a>",synthetic:false,types:["cassowary::RelationalOperator"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"cassowary/enum.AddConstraintError.html\" title=\"enum cassowary::AddConstraintError\">AddConstraintError</a>",synthetic:false,types:["cassowary::AddConstraintError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"cassowary/enum.RemoveConstraintError.html\" title=\"enum cassowary::RemoveConstraintError\">RemoveConstraintError</a>",synthetic:false,types:["cassowary::RemoveConstraintError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"cassowary/enum.AddEditVariableError.html\" title=\"enum cassowary::AddEditVariableError\">AddEditVariableError</a>",synthetic:false,types:["cassowary::AddEditVariableError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"cassowary/enum.RemoveEditVariableError.html\" title=\"enum cassowary::RemoveEditVariableError\">RemoveEditVariableError</a>",synthetic:false,types:["cassowary::RemoveEditVariableError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"cassowary/enum.SuggestValueError.html\" title=\"enum cassowary::SuggestValueError\">SuggestValueError</a>",synthetic:false,types:["cassowary::SuggestValueError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
